language: php

php: [5.3, 5.4, 5.5]


branches:
  only:
    - master

before_script:
  - composer self-update
  - composer install --dev --prefer-source --no-progress -n
  
script: 'vendor/bin/behat -c skeletontest/behat.yml -p=simple'
